using PinnyNotes.Core.Enums;

namespace PinnyNotes.Core.DataTransferObjects;

public record SettingsDataDto(
     int Id,

     bool StartWithWindows,
     StartupBehaviour StartupBehaviour,
     NewInstanceBehaviour NewInstanceBehaviour,
     bool ShowTrayIcon,
     bool CheckForUpdates,

     double DefaultNoteWidth,
     double DefaultNoteHeight,
     StartupPosition StartupPosition,
     bool PinnedByDefault,
     MinimizeMode MinimizeMode,
     VisibilityMode VisibilityMode,
     bool HideTitleBar,
     bool CycleColours,
     ColourMode ColourMode,
     TransparencyMode TransparencyMode,
     bool OpaqueWhenFocused,
     double OpaqueOpacity,
     double TransparentOpacity,

     bool SpellCheck,
     bool AutoIndent,
     bool NewLineAtEnd,
     bool KeepNewLineVisible,
     bool WrapText,
     string StandardFontFamily,
     string MonoFontFamily,
     bool UseMonoFont,
     bool TabUsesSpaces,
     bool ConvertIndentationOnPaste,
     int TabWidth,
     CopyAction CopyAction,
     bool TrimTextOnCopy,
     CopyAction CopyAltAction,
     bool TrimTextOnAltCopy,
     CopyFallbackAction CopyFallbackAction,
     bool TrimTextOnFallbackCopy,
     CopyFallbackAction CopyAltFallbackAction,
     bool TrimTextOnAltFallbackCopy,
     bool CopyTextOnHighlight,
     PasteAction PasteAction,
     bool TrimTextOnPaste,
     PasteAction PasteAltAction,
     bool TrimTextOnAltPaste,
     bool MiddleClickPaste,

     ToolState Base64State,
     ToolState BracketState,
     ToolState CaseState,
     ToolState ColourState,
     ToolState DateTimeState,
     ToolState GibberishState,
     ToolState GuidState,
     ToolState HashState,
     ToolState HTMLEntityState,
     ToolState IndentState,
     ToolState JoinState,
     ToolState JSONState,
     ToolState ListState,
     ToolState QuoteState,
     ToolState RemoveState,
     ToolState SlashState,
     ToolState SortState,
     ToolState SplitState,
     ToolState TrimState,
     ToolState UrlState
);
