//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinnyNotes.WpfUi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class ToolSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToolSettings defaultInstance = ((ToolSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToolSettings())));
        
        public static ToolSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Base64ToolEnabled {
            get {
                return ((bool)(this["Base64ToolEnabled"]));
            }
            set {
                this["Base64ToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Base64ToolFavourite {
            get {
                return ((bool)(this["Base64ToolFavourite"]));
            }
            set {
                this["Base64ToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BracketToolEnabled {
            get {
                return ((bool)(this["BracketToolEnabled"]));
            }
            set {
                this["BracketToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BracketToolFavourite {
            get {
                return ((bool)(this["BracketToolFavourite"]));
            }
            set {
                this["BracketToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CaseToolEnabled {
            get {
                return ((bool)(this["CaseToolEnabled"]));
            }
            set {
                this["CaseToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CaseToolFavourite {
            get {
                return ((bool)(this["CaseToolFavourite"]));
            }
            set {
                this["CaseToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DateTimeToolEnabled {
            get {
                return ((bool)(this["DateTimeToolEnabled"]));
            }
            set {
                this["DateTimeToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DateTimeToolFavourite {
            get {
                return ((bool)(this["DateTimeToolFavourite"]));
            }
            set {
                this["DateTimeToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GibberishToolEnabled {
            get {
                return ((bool)(this["GibberishToolEnabled"]));
            }
            set {
                this["GibberishToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GibberishToolFavourite {
            get {
                return ((bool)(this["GibberishToolFavourite"]));
            }
            set {
                this["GibberishToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HashToolEnabled {
            get {
                return ((bool)(this["HashToolEnabled"]));
            }
            set {
                this["HashToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HashToolFavourite {
            get {
                return ((bool)(this["HashToolFavourite"]));
            }
            set {
                this["HashToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HtmlEntityToolEnabled {
            get {
                return ((bool)(this["HtmlEntityToolEnabled"]));
            }
            set {
                this["HtmlEntityToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HtmlEntityToolFavourite {
            get {
                return ((bool)(this["HtmlEntityToolFavourite"]));
            }
            set {
                this["HtmlEntityToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IndentToolEnabled {
            get {
                return ((bool)(this["IndentToolEnabled"]));
            }
            set {
                this["IndentToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndentToolFavourite {
            get {
                return ((bool)(this["IndentToolFavourite"]));
            }
            set {
                this["IndentToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JoinToolEnabled {
            get {
                return ((bool)(this["JoinToolEnabled"]));
            }
            set {
                this["JoinToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JoinToolFavourite {
            get {
                return ((bool)(this["JoinToolFavourite"]));
            }
            set {
                this["JoinToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JsonToolEnabled {
            get {
                return ((bool)(this["JsonToolEnabled"]));
            }
            set {
                this["JsonToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JsonToolFavourite {
            get {
                return ((bool)(this["JsonToolFavourite"]));
            }
            set {
                this["JsonToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ListToolEnabled {
            get {
                return ((bool)(this["ListToolEnabled"]));
            }
            set {
                this["ListToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListToolFavourite {
            get {
                return ((bool)(this["ListToolFavourite"]));
            }
            set {
                this["ListToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuoteToolEnabled {
            get {
                return ((bool)(this["QuoteToolEnabled"]));
            }
            set {
                this["QuoteToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuoteToolFavourite {
            get {
                return ((bool)(this["QuoteToolFavourite"]));
            }
            set {
                this["QuoteToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveToolEnabled {
            get {
                return ((bool)(this["RemoveToolEnabled"]));
            }
            set {
                this["RemoveToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoveToolFavourite {
            get {
                return ((bool)(this["RemoveToolFavourite"]));
            }
            set {
                this["RemoveToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SlashToolEnabled {
            get {
                return ((bool)(this["SlashToolEnabled"]));
            }
            set {
                this["SlashToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SlashToolFavourite {
            get {
                return ((bool)(this["SlashToolFavourite"]));
            }
            set {
                this["SlashToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortToolEnabled {
            get {
                return ((bool)(this["SortToolEnabled"]));
            }
            set {
                this["SortToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SortToolFavourite {
            get {
                return ((bool)(this["SortToolFavourite"]));
            }
            set {
                this["SortToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SplitToolEnabled {
            get {
                return ((bool)(this["SplitToolEnabled"]));
            }
            set {
                this["SplitToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SplitToolFavourite {
            get {
                return ((bool)(this["SplitToolFavourite"]));
            }
            set {
                this["SplitToolFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrimToolEnabled {
            get {
                return ((bool)(this["TrimToolEnabled"]));
            }
            set {
                this["TrimToolEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrimToolFavourite {
            get {
                return ((bool)(this["TrimToolFavourite"]));
            }
            set {
                this["TrimToolFavourite"] = value;
            }
        }
    }
}
