using PinnyNotes.Core.Enums;

namespace PinnyNotes.Core.Models;

public record SettingsDataModel(
     int Id,

     bool ShowTrayIcon,
     bool CheckForUpdates,

     double DefaultNoteWidth,
     double DefaultNoteHeight,
     StartupPositions StartupPosition,
     MinimizeModes MinimizeMode,
     VisibilityModes VisibilityMode,
     bool HideTitleBar,
     bool CycleColors,
     ColorModes ColorMode,
     TransparencyModes TransparencyMode,
     bool OpaqueWhenFocused,
     double OpaqueOpacity,
     double TransparentOpacity,

     bool SpellCheck,
     bool AutoIndent,
     bool NewLineAtEnd,
     bool KeepNewLineVisible,
     bool WrapText,
     string StandardFontFamily,
     string MonoFontFamily,
     bool UseMonoFont,
     bool TabUsesSpaces,
     bool ConvertIndentationOnPaste,
     int TabWidth,
     CopyActions CopyAction,
     bool TrimTextOnCopy,
     CopyActions CopyAltAction,
     bool TrimTextOnAltCopy,
     CopyFallbackActions CopyFallbackAction,
     bool TrimTextOnFallbackCopy,
     CopyFallbackActions CopyAltFallbackAction,
     bool TrimTextOnAltFallbackCopy,
     bool CopyTextOnHighlight,
     PasteActions PasteAction,
     bool TrimTextOnPaste,
     PasteActions PasteAltAction,
     bool TrimTextOnAltPaste,
     bool MiddleClickPaste,

     ToolStates Base64State,
     ToolStates BracketState,
     ToolStates CaseState,
     ToolStates ColorState,
     ToolStates DateTimeState,
     ToolStates GibberishState,
     ToolStates HashState,
     ToolStates HTMLEntityState,
     ToolStates IndentState,
     ToolStates JoinState,
     ToolStates JSONState,
     ToolStates ListState,
     ToolStates QuoteState,
     ToolStates RemoveState,
     ToolStates SlashState,
     ToolStates SortState,
     ToolStates SplitState,
     ToolStates TrimState,
     ToolStates UrlState
);
